### PR TITLE
update to the python3

### PR DESCRIPTION
**Pull request by EmadDeve20**
hi @antonioCoco I finished https://github.com/antonioCoco/SharPyShell/issues/10
:D and i liked Your project but your source needs comments
what are you think?

### CODE REVIEW

**Comment by antonioCoco** [comment]
all the strings needs to be casted to binary otherwise the encryption of the channel will be broken. 

Did you tested the framework against any IIS webserver?

**Comment by EmadDeve20** [comment]
I can not test it because I do not know how your project works.
I just repaired python2 to python3.

**Comment by EmadDeve20** [comment]
so you can test my edit and if you see a problem tell me I so happy about it :D

**Comment by antonioCoco** [comment]
Well this is not a "repair". You just changed the parenthesis in the print and the string interpolations. All the modules code is unchanged.

Anyway i don't merge untested code. If you want to contribute please ensure to test the code.

**Pull request closed without merging**
